Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b0d53c279acc90
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value: my-instance-1
